### ISSUE TITLE
Issue with proportion of variance in prcomp_irlba with scaling

### ISSUE THREAD

**Issue by Baurice** [bwlewis/irlba#32]
I believe this is related to [issue #23](https://github.com/bwlewis/irlba/issues/23). The calculated proportion of variance is pretty consistent with `stats::prcomp` without scaling (fixed after #23), but when `scale. = TRUE` it differs widely. I believe the solution would be to check for `scale.` and use the scaled matrix to calculate the proportion of variance if `scale. = TRUE`.

Based on your example, but using `scale. = TRUE`:
```
set.seed(1)
x  <- matrix(rnorm(200), nrow=20)
p1 <- prcomp_irlba(x, n=3, scale. = TRUE)
summary(p1)
```
```
Importance of components:
                          PC1    PC2    PC3
Standard deviation     1.5308 1.3415 1.3121
Proportion of Variance 0.2769 0.2126 0.2034
Cumulative Proportion  0.2769 0.4895 0.6929
```
```
p2 <- prcomp(x, tol=0.7, scale = TRUE)
summary(p2)
```

```
Importance of first k=4 (out of 10) components:
                          PC1    PC2    PC3    PC4
Standard deviation     1.5308 1.3415 1.3121 1.1814
Proportion of Variance 0.2343 0.1800 0.1722 0.1396
Cumulative Proportion  0.2343 0.4143 0.5864 0.7260
```

**Using scaled matrix:**

```
# Proportion of Variance:
round(summary(p1)$importance[1,]**2 / 
sum( apply( Re(scale(x, center=colMeans(x), scale=TRUE)) , 2, stats::var ) ), 4)
```
```
   PC1    PC2    PC3 
0.2343 0.1800 0.1722
``` 

```
# Cumulative Proportion:
round(cumsum(summary(p1)$importance[1,]**2 / 
sum( apply( Re(scale(x, center=colMeans(x), scale=TRUE)) , 2, stats::var ) )), 4)
```
```
   PC1    PC2    PC3 
0.2343 0.4143 0.5864 
```

**Comment by bwlewis** [comment]
Thanks for this great catch!

The bug is here in this line:  https://github.com/bwlewis/irlba/blob/master/R/prcomp.R#L112   which uses the unscaled matrix.

Yes, your proposed fix works, but introduces other problems. In particular, this:
`Re(scale(x, center=colMeans(x), scale=TRUE))` can be terribly expensive, or even not possible for huge matrices--and those are precisely the problems irlba is designed to work for. For instance, a huge sparse matrix would be filled in by this step, possibly blowing past available computer memory. Here is a short example:
```{r}
library(Matrix)
i = sample(5000, 5000, replace=TRUE)
j = sample(5000, 5000, replace=TRUE)
x = sparseMatrix(i, j, x=rnorm(5000))
object.size(x)
## 81424 bytes

object.size(Re(scale(x, center=colMeans(x), scale=TRUE)))
## ...long pause...
## 200040672 bytes
```

I'm thinking about an alternative, which should be possible. If you come up with something, let me know. I'd like to get 2.3.2 out to CRAN this week, but I want your fix in there too!

Thanks, again...

**Comment by bwlewis** [comment]
I just realized that the line with the bug, https://github.com/bwlewis/irlba/blob/master/R/prcomp.R#L112, is also blowing the matrix up. So that also needs fixing...

**Comment by bwlewis** [comment]
I guess that the fix will use a for loop, something like:
`sum(vapply(1:ncol(x), function(i) var(x[,i]), 1))`  or 
`s=0;for(i in 1:ncol(x)) s= s+var(x[,i])}`, but then adjusting for scaling/centering as specified.

**Comment by bwlewis** [comment]
OK, I think the last commit https://github.com/bwlewis/irlba/commit/8cd2e94bb79d8f02817f87bc6e7b288713ec72ed  fixes the bug, and also improves the performance for large sparse matrices. Try it out, and thanks for catching this!
