### ISSUE TITLE
Why do i have different results for irlba$v and prcomp_irlba$rotation for the same matrix?

### ISSUE THREAD

**Issue by Fackie** [bwlewis/irlba#39]
set.seed(1)
x  <- matrix(rnorm(200), nrow=20)
p1 <- prcomp_irlba(x, n=3)
p3 <- irlba(A=x, nv=3)
and i got p1$rotation ：
![image](https://user-images.githubusercontent.com/24207392/43130950-70677aec-8f6a-11e8-9312-f6033fa2a878.png)
p3$v:
![image](https://user-images.githubusercontent.com/24207392/43130987-848f701a-8f6a-11e8-80cb-57ae9970af7c.png)

If im not wrong ,maybe  it should have X=UΔV‘ (SVD) and UΔ = XV(PCA)

**Comment by Fackie** [comment]
since i even found that 
![image](https://user-images.githubusercontent.com/24207392/43131493-c79890c0-8f6b-11e8-8ad1-53eba1d5e3c6.png)

**Comment by bwlewis** [comment]
Because they don't compute the same decomposition by default. It's equivalent to the difference between `svd` and `prcomp`.  `irlba` computes a singular value decomposition. `prcomp_irlba` computes a principal component decomposition with centering.

Try, for instance,

```{r}
set.seed(1)
x <- matrix(rnorm(200), nrow=20)
p1 <- prcomp_irlba(x, n=3)
p3 <- irlba(A=x, nv=3)
p2 <- irlba(x, nv=3, center=colMeans(x))
```
Now `p3$v` and `p1$rotation` agree up to sign.

**Comment by Fackie** [comment]
Sorry I just forget this question cause I found the error myself later....But still great thanks!!!!
